services:
  wordpress:
    image: wordpress:php8.2
    ports:
      - '127.0.0.11:80:80'
    volumes:
      - 'wordpress:/var/www/html'
      - './plugins/jedi-plugins:/var/www/html/wp-content/plugins/jedi-plugins'
      - './themes/jediholonet:/var/www/html/wp-content/themes/jediholonet'
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=jediholo
      - WORDPRESS_DB_PASSWORD=jediholo
      - WORDPRESS_DB_NAME=jedi-wordpress
      - WORDPRESS_CONFIG_EXTRA=define('WP_REDIS_HOST','redis');
  cli:
    image: wordpress:cli-php8.2
    user: '33:33'
    volumes:
      - 'wordpress:/var/www/html'
      - './plugins/jedi-plugins:/var/www/html/wp-content/plugins/jedi-plugins'
      - './themes/jediholonet:/var/www/html/wp-content/themes/jediholonet'
      - './wp-setup.sh:/usr/local/bin/wp-setup.sh'
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=jediholo
      - WORDPRESS_DB_PASSWORD=jediholo
      - WORDPRESS_DB_NAME=jedi-wordpress
      - WORDPRESS_CONFIG_EXTRA=define('WP_REDIS_HOST','redis');
    profiles:
      - setup
  mysql:
    image: mariadb:10.11
    ports:
      - '127.0.0.11:3306:3306'
    volumes:
      - 'mysql:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=jediholo
      - MYSQL_USER=jediholo
      - MYSQL_PASSWORD=jediholo
      - MYSQL_DATABASE=jedi-wordpress
  redis:
    image: redis:6.2
volumes:
  mysql:
  wordpress:
